export const statusTone: Record<string, string> = {
  "Open": "info",
  "Sourcing": "info",
  "Interviewing": "warn",
  "Offer": "warn",
  "Filled": "success",
  "On hold": "muted",
  "Closed": "muted",
  "Available": "success",
  "Active": "info",
  "Passive": "muted",
  "Placed": "success",
  "Unavailable": "muted",
  "Draft": "muted",
  "Submitted": "info",
  "Client reviewed": "info",
  "Interview requested": "warn",
  "Rejected": "danger",
  "Offer pending": "warn",
  "Active client": "success",
  "Prospect": "info",
  "Inactive client": "muted",
  "Target account": "warn",
  "In progress": "warn",
  "Completed": "success",
  "Overdue": "danger",
  "Scheduled": "info",
  "Pending start": "warn",
  "Urgent": "danger",
  "High": "warn",
  "Medium": "info",
  "Low": "muted",
};